{% set name = "gdstk" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/heitzmann/gdstk.git
  git_depth: 1
  # - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #   folder: pypi
  #   sha256: a2bc3ed4ea05ddb8e6a50da562065c98a307421425a27284c7bdd42cf7508929
  # - url: https://github.com/heitzmann/{{ name }}/archive/v{{ version }}.tar.gz
  #   folder: github
  #   sha256: 7d4b32c0569057fe19c485d1fbc5880fafec1bf89133e4f20f8c41e44e13fffe

build:
  number: 0
  script: {{ PYTHON }} -m pip install ./pypi -vv

requirements:
  build:
    - cmake >=3.13.0
    - {{ compiler('cxx') }}
  host:
    - liblapack
    - zlib
    - numpy >=1.14
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  source_files:
    - github/tests/*
  commands:
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/heitzmann/gdstk
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Gdstk (GDSII Tool Kit) is a C++/Python library for creation and manipulation of GDSII and OASIS files.

  description: |
    Gdstk (GDSII Tool Kit) is a C++ library for creation and manipulation of
    GDSII and OASIS files. It is also available as a Python module meant to
    be a successor to Gdspy.  Key features for the creation of complex CAD
    layouts are included: boolean operations on polygons (AND, OR, NOT, XOR)
    based on clipping algorithm; polygon offset (inward and outward rescaling
    of polygons); efficient point-in-polygon solutions for large array sets.
  doc_url: https://heitzmann.github.io/gdstk/
  dev_url: https://github.com/heitzmann/gdstk

extra:
  recipe-maintainers:
    - heitzmann
    - wshanks
