{% set name = "gdstk" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    folder: pypi
    sha256: 99f4757091d854d822aa153c0a1877ccb17351a81116a778072381bc7e69052a
  - url: https://github.com/heitzmann/{{ name }}/archive/v{{ version }}.tar.gz
    folder: github
    sha256: b128685fc4049b9248f5231a1ffa0988a8fc6ed7965fe07d51b22d92dbdbb6cc

build:
  number: 1
  script: {{ PYTHON }} -m pip install ./pypi -vv

requirements:
  build:
    - cmake >=3.13.0
    - {{ compiler('cxx') }}
  host:
    - liblapack
    - numpy >=1.14
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  source_files:
    - github/tests/*
  commands:
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/heitzmann/gdstk
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Gdstk (GDSII Tool Kit) is a C++ library for creation and manipulation of GDSII stream files.

  description: |
    Gdstk (GDSII Tool Kit) is a C++ library for creation and manipulation of
    GDSII stream files. It is also available as a Python module meant to be a
    successor to Gdspy.  Key features for the creation of complex CAD layouts
    are included: 1. Boolean operations on polygons (AND, OR, NOT, XOR) based
    on clipping algorithm; 2. Polygon offset (inward and outward rescaling of
    polygons); and 3. Efficient point-in-polygon solutions for large array
    sets.
  doc_url: https://heitzmann.github.io/gdstk/
  dev_url: https://github.com/heitzmann/gdstk

extra:
  recipe-maintainers:
    - heitzmann
    - wshanks
