{% set name = "gdstk" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/heitzmann/{{ name }}/archive/v{{ version }}.tar.gz
  folder: gdstk
  sha256: 257b665cda27bef6e85d5df5d33277377e50c24c958a1302ad65978bee7f49e6

build:
  number: 0
  script: {{ PYTHON }} -m pip install ./gdstk -vv

requirements:
  build:
    - cmake >=3.14.0
    - {{ compiler('cxx') }}
    - make
  host:
    - zlib
    - numpy >=1.14
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  source_files:
    - gdstk/tests/*
  commands:
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/heitzmann/gdstk
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Gdstk (GDSII Tool Kit) is a C++/Python library for creation and manipulation of GDSII and OASIS files.

  description: |
    Gdstk (GDSII Tool Kit) is a C++ library for creation and manipulation of
    GDSII and OASIS files.  It is also available as a Python module meant to
    be a successor to Gdspy.  Key features for the creation of complex CAD
    layouts are included: boolean operations on polygons (AND, OR, NOT, XOR)
    based on clipping algorithm; polygon offset (inward and outward rescaling
    of polygons); efficient point-in-polygon solutions for large array sets.
  doc_url: https://heitzmann.github.io/gdstk/
  dev_url: https://github.com/heitzmann/gdstk

extra:
  recipe-maintainers:
    - heitzmann
    - wshanks
