{% set name = "gdstk" %}
{% set version = "0.9.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/heitzmann/{{ name }}/archive/v{{ version }}.tar.gz
  folder: gdstk
  sha256: 287d9c4af0770cff9697273b24dbd0aa007e4ba86656832517d6d3d2c3587425

build:
  number: 1
  script: {{ PYTHON }} -m pip install ./gdstk -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.14.0
    - {{ compiler('cxx') }}
    - make
  host:
    - numpy
    - python >=3.8
    - pip
    - setuptools >=42
    - qhull
    - wheel
    - zlib
  run:
    - {{ pin_compatible('numpy') }}
    - python >=3.8
    - typing-extensions  # [py<311]

test:
  source_files:
    - gdstk/tests/*
  commands:
    - pytest                                    # [python_impl != 'pypy']
    - pytest -k "not test_roundtrip_path_ends"  # [python_impl == 'pypy']
  requires:
    - pytest

about:
  home: https://github.com/heitzmann/gdstk
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Gdstk (GDSII Tool Kit) is a C++/Python library for creation and manipulation of GDSII and OASIS files.

  description: |
    Gdstk (GDSII Tool Kit) is a C++ library for creation and manipulation of
    GDSII and OASIS files.  It is also available as a Python module meant to
    be a successor to Gdspy.  Key features for the creation of complex CAD
    layouts are included: boolean operations on polygons (AND, OR, NOT, XOR)
    based on clipping algorithm; polygon offset (inward and outward rescaling
    of polygons); efficient point-in-polygon solutions for large array sets.
  doc_url: https://heitzmann.github.io/gdstk/
  dev_url: https://github.com/heitzmann/gdstk

extra:
  recipe-maintainers:
    - heitzmann
    - wshanks
